name: Update Notion "Approved by" on PR Approval to develop

on:
  pull_request_review:
    types: [ submitted ]

jobs:
  update-notion:
    if: github.event.review.state == 'approved' && github.event.pull_request.base.ref == 'develop'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run Notion updater
        run: node scripts/update-notion-approved-by.js
        env:
          NOTION_SECRET: ${{ secrets.NOTION_SECRET }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
          MR_TITLE: ${{ github.event.pull_request.title }}
          MR_AUTHOR: ${{ github.event.review.user.login }}
